language: java
branches:
  only:
  - master
script:
- ./gradlew --stacktrace sonarqube -Dsonar.organization=duckasteroid-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=913dc2f41588fe61c36d6641cb510b9cded7cb90
- ./gradlew bintrayUpload
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  # Sonar user
  - secure: izl1fDcLEMAb18Awn7ZTkyF1JXwMKo4XoCKbJ4kO/RHubiEl3liTwoOMR2IX8WKK0wpx+FumyTFZ0LvZGW/mFNGOnpCwe2IQn81v+Haosai+iSOFyLqN/OGRM6W0oXgurN48e2rgjvTjvjvaetUy+bVp9x2UvjDa3R/LcPwojrEvHAsC0S8pMPHRCuHjjL/q5P1n13FKR3JstnTSaY/KKCwcJIrFpV70bFSh+sN+0nqb0l2LwYiF2OJwYEDJk3S3efpVVNr/293xt5S94e+dcgSHIh5qmYwTp8pXR5oq0uIBFOB3IbAlCBkjOEephk3GZPmneONUXnzLb4ur9ekZPywpHIfdDU0n0rfbBTnmrPldwELekOJvK/R1ANZqI/Fo8h2gQuw6Oj+P+ahp7/MiI40Y1m8h5VGdH04IrwWYYGr5w5yInooe+zgggqujd5w4G2HkVcIkdjSSo4LexMu8j0nvBYnepGbJw3Oy/lQEesCFPx3EDKOa0TzvJeeuKxBexhJPTtEXtGdmf9r26Y24kk5TnTU4IxJj0P5rWExnWx7wf9Q8SS8QRTkmD5Fl8cMMaCbyDJqqlvAOLosd+txfHq27RVuAb/twJ/KLMwXc7XUhSiWwK8JB9Enq4XkZ2Yaqa3NaA/tXMPfCLc7emzTC7bnrBK3CBhB1fFzxRk+eYHA=
  # Sonar Key
  - secure: XR/3SVieNipIdYx/0eaumVy64Gx6I58Y62+ITUBRi4N4Ob0kDxVCczTpUmEmsd2kJ7UoTDUH0idXJd2x3Ac+iVvmceqO3gKTCSe48u8BNH6oAAP8o1jcRQ9LxuRC/TdCtqzx9Ymb6ZNN44i/LuAetNEP8QyAaVIwjQuCEAiX+YYxKW8YsBVK8aPBdtiD/9qDhYejNm6jrtYfHtMs3xX40u4W2E/qBjJKtMCJ1iXMiNWwjjA3IPebzdRDFJm29gBywHV+Wa9ArXuYVMXcXZ+LB0GNrqOef7XBpAG/ut2lrdaSsDE9JOBZX0X9vZ2An2Xu8IriKZjldQYXabB4pTeoUGUfCYq46lzGLTbUtZc4ANfWMI/LX0hENLSdirAciYi/lyTMQ2fx+Zd6PF6RlEVaB/qs5oSzWNlIWd+CsL0Fquh2+Q1QZvdX6dul7poXHof20JHWAubZrG1tUnINJIv+A9MH+jHPSlIuZvMxVbmZUidTIAR2WFHm907zT0PzRBHOb6BQtAOWUNiXBTPimeCIdxawjbvQkGeHBQttnS59ZBhRkzlrmA6VCZ2+OPkLTH9OxXpUZKTWu9VCyVRdprWhuCZb5htUsIN4sdyZySvu6TVGm8YPCF5hbmrYO2QJaWyKuMthz/BEVfIOVMjmDh+WVuBIdsJoptuhBlCpeE/VAjg=

